import { useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { Link, useNavigate } from 'react-router-dom'

const API = 'http://127.0.0.1:8000'
const TOKEN = 'interior_design_token'
type Role = 'customer' | 'employee' | 'admin'

async function authRequest<T>(path: string, options: RequestInit = {}): Promise<T> {
  const headers = new Headers(options.headers)
  if (options.body && !(options.body instanceof URLSearchParams)) headers.set('Content-Type', 'application/json')
  const response = await fetch(`${API}${path}`, { ...options, headers })
  if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.detail || `Request failed (${response.status})`) }
  return response.json()
}
function RoleTabs({ roles, selected, onSelect }: { roles: Role[]; selected: Role; onSelect: (role: Role) => void }) { return <div className="role-tabs" role="tablist" aria-label="Account role">{roles.map(role => <button type="button" role="tab" aria-selected={selected === role} className={selected === role ? 'selected' : ''} onClick={() => onSelect(role)} key={role}>{role[0].toUpperCase() + role.slice(1)}</button>)}</div> }
function AuthFrame({ title, caption, children }: { title: string; caption: string; children: ReactNode }) { return <main className="auth-page"><Link className="brand-mark" to="/">AVA<span>•</span></Link><div className="auth-card"><span className="eyebrow">Interior Design System</span><h1>{title}</h1><p>{caption}</p>{children}</div><div className="auth-aside">“A room is not just a room.<br />It is a point of view.”</div></main> }
function Field({ label, value, onChange, type = 'text', required = false, optional = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean; optional?: boolean }) { return <label className="field"><span>{label} {optional && <small>(optional)</small>}</span><input type={type} value={value} onChange={event => onChange(event.target.value)} required={required} /></label> }
function ErrorBox({ message }: { message: string }) { return message ? <div className="form-error">{message}</div> : null }

export function LoginFlow() {
  const navigate = useNavigate(); const [role, setRole] = useState<Role>('customer'); const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setBusy(true); try { const data = await authRequest<{ access_token: string }>('/auth/login', { method: 'POST', body: new URLSearchParams({ username, password }) }); const claims = JSON.parse(atob(data.access_token.split('.')[1])); if (claims.role !== role) throw new Error(`This account is not a ${role} account.`); localStorage.setItem(TOKEN, data.access_token); navigate('/dashboard') } catch (err) { setError(err instanceof Error ? err.message : 'Unable to log in') } finally { setBusy(false) } }
  return <AuthFrame title="Welcome back" caption="Choose your workspace role, then continue."><div className="auth-flow"><RoleTabs roles={['customer', 'employee', 'admin']} selected={role} onSelect={setRole} /><p className="role-help">Your role is checked against your backend account.</p><form className="auth-form" onSubmit={submit}><Field label="Username" value={username} onChange={setUsername} required /><Field label="Password" type="password" value={password} onChange={setPassword} required /><ErrorBox message={error} /><button className="button primary full" disabled={busy}>{busy ? 'Signing in…' : 'Sign in'} ↗</button></form>{role !== 'admin' ? <p className="form-switch">Need an account? <Link to="/register">Create a {role} account</Link></p> : <p className="role-help admin-note">Admin accounts are created by the system administrator.</p>}</div></AuthFrame>
}

export function RegisterFlow() {
  const navigate = useNavigate(); const [role, setRole] = useState<Role>('customer'); const [step, setStep] = useState<1 | 2>(1); const [credentials, setCredentials] = useState({ username: '', password: '', confirm: '' }); const [profile, setProfile] = useState({ name: '', phone: '', email: '' }); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [busy, setBusy] = useState(false)
  const setCredential = (key: keyof typeof credentials, value: string) => setCredentials(current => ({ ...current, [key]: value })); const setProfileValue = (key: keyof typeof profile, value: string) => setProfile(current => ({ ...current, [key]: value }))
  function chooseRole(next: Role) { setRole(next); setError(''); setSuccess(''); setStep(1) }
  function nextStep(event: FormEvent) { event.preventDefault(); setError(''); if (role === 'employee') { setError('Employee registration is not available from this frontend. An admin must create the employee account first.'); return } if (credentials.password !== credentials.confirm) { setError('Password and Confirm Password must match.'); return } setSuccess('Credentials accepted. Complete your profile to create the account.'); setStep(2) }
  async function finish(event: FormEvent) { event.preventDefault(); setError(''); if (!profile.name || !profile.phone) { setError('Name and phone number are required.'); return } if (!profile.email) { setError('Email is required by the current backend registration API.'); return } setBusy(true); try { await authRequest('/auth/register', { method: 'POST', body: JSON.stringify({ username: credentials.username, password: credentials.password, customer_name: profile.name, phone_no: profile.phone, email: profile.email }) }); setSuccess('Account created successfully! Redirecting to login…'); window.setTimeout(() => navigate('/login'), 800) } catch (err) { setError(err instanceof Error ? err.message : 'Unable to create account') } finally { setBusy(false) } }
  return <AuthFrame title={step === 1 ? 'Create your account' : 'Tell us about you'} caption={step === 1 ? 'Start with secure account credentials.' : 'One last step before your workspace is ready.'}><div className="auth-flow"><div className="stepper"><span className={step === 1 ? 'current' : 'complete'}>01 <small>Credentials</small></span><i /><span className={step === 2 ? 'current' : ''}>02 <small>Profile</small></span></div>{step === 1 ? <form className="auth-form" onSubmit={nextStep}><RoleTabs roles={['customer', 'employee']} selected={role} onSelect={chooseRole} />{role === 'employee' && <div className="limitation-note">Employee accounts are created through the protected admin-only <code>POST /employees</code> API. No public employee registration endpoint exists.</div>}<Field label="Username" value={credentials.username} onChange={v => setCredential('username', v)} required /><div className="field-grid"><Field label="Password" type="password" value={credentials.password} onChange={v => setCredential('password', v)} required /><Field label="Confirm Password" type="password" value={credentials.confirm} onChange={v => setCredential('confirm', v)} required /></div><ErrorBox message={error} /><ErrorBox message={success} /><button className="button primary full" disabled={role === 'employee'}>Continue to profile ↗</button></form> : <form className="auth-form" onSubmit={finish}><div className="success-banner">{success || 'Account credentials ready.'}</div><Field label="Name" value={profile.name} onChange={v => setProfileValue('name', v)} required /><Field label="Phone Number" value={profile.phone} onChange={v => setProfileValue('phone', v)} required /><Field label="Email" type="email" value={profile.email} onChange={v => setProfileValue('email', v)} optional /><p className="field-note">The current backend requires an email address to create a customer.</p><ErrorBox message={error} /><div className="form-actions"><button type="button" className="button ghost" onClick={() => { setStep(1); setError(''); setSuccess('') }}>← Back</button><button className="button primary" disabled={busy}>{busy ? 'Creating…' : 'Finish registration'}</button></div></form>}<p className="form-switch">Already registered? <Link to="/login">Sign in</Link></p></div></AuthFrame>
}
